# Generated by Django 3.2.9 on 2021-11-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'video_table',
            },
        ),
        migrations.CreateModel(
            name='Video_word',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('date', models.DateField()),
                ('video_id', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, to='app.video')),
            ],
            options={
                'db_table': 'video_word_table',
            },
        ),
    ]
